name: Push Helm Chart to S3

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.10.3'

      - name: Package Helm Chart
        run: |
          helm package chart/ --destination .

      - name: Install Helm S3 plugin
        run: helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: Add Briefer's S3 repo
        run: helm repo add briefer-public-helm s3://briefer-helm

      - name: Upload Helm Chart to S3
        run: |
          helm s3 push briefer-*.tgz briefer-public-helm
